### ISSUE TITLE
Plugin doesn't load

### ISSUE THREAD

**Issue by solowanna** [Jallah123/hue-ambiance#2]
After i installed the plugin from the plugin-hub i dont see the config panel.

In the logs i see the following:
2022-08-04 21:51:08 [pool-3-thread-1] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "phillip-hue-integration" version "c260c0fc" commit "c260c0fc3e4ce5cff13fed7052d92367dda01102"
2022-08-04 21:51:08 [pool-3-thread-1] WARN  n.r.c.e.ExternalPluginManager - Unable to start or load external plugin "phillip-hue-integration"
java.lang.reflect.InvocationTargetException: null
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
	at net.runelite.client.externalplugins.ExternalPluginManager.refreshPlugins(ExternalPluginManager.java:340)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: net.runelite.client.plugins.PluginInstantiationException: java.lang.IllegalArgumentException: protocol = http host = null
	at net.runelite.client.externalplugins.ExternalPluginManager.lambda$refreshPlugins$3(ExternalPluginManager.java:351)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: net.runelite.client.plugins.PluginInstantiationException: java.lang.IllegalArgumentException: protocol = http host = null
	at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:462)
	at net.runelite.client.externalplugins.ExternalPluginManager.lambda$refreshPlugins$3(ExternalPluginManager.java:346)
	... 13 common frames omitted
Caused by: java.lang.IllegalArgumentException: protocol = http host = null
	at java.base/sun.net.spi.DefaultProxySelector.select(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.URL.openStream(Unknown Source)
	at com.fasterxml.jackson.core.TokenStreamFactory._optimizedStreamFromURL(TokenStreamFactory.java:211)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1057)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3479)
	at io.github.zeroone3010.yahueapi.Hue.refresh(Hue.java:138)
	at io.github.zeroone3010.yahueapi.Hue.doInitialDataLoadIfRequired(Hue.java:122)
	at io.github.zeroone3010.yahueapi.Hue.getRoomByName(Hue.java:228)
	at com.hueambiance.HueAmbiancePlugin.startUp(HueAmbiancePlugin.java:49)
	at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:440)
	... 14 common frames omitted

**Comment by solowanna** [comment]
A restart of the client fixes the problem.

**Comment by Jallah123** [comment]
fixed in next version
